// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odtwlejkokzcdvuuvbhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kdHdsZWprb2t6Y2R2dXV2YmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTA2NTksImV4cCI6MjA3MDY4NjY1OX0.G3g3Hn21slp61n8nONodQzISVv-vpDcRe1_3QdLqlIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});